### ISSUE TITLE
启动报错啊

### ISSUE THREAD

**Issue by SanpLee** [JoV5/react-starter#3]
F:\WebpackTest\reactProject\config\webpack.config.dev.js:207
      names: ['main', 'manifest'].concat(Object.keys(appConfigEntry))
                                                ^

TypeError: Cannot convert undefined or null to object
    at Object.<anonymous> (F:\WebpackTest\reactProject\config\webpack.config.dev.js:207:49)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\WebpackTest\reactProject\scripts\start.js:24:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)

**Comment by JoV5** [comment]
恩，这个报的错不太对，已经修复。
不过因为示例是多入口的，`npm start`其中一个项目才能正常启动，比如`npm start -- app=react-router`。
如果已经安装`create-react-app`的话，可以使用[mult-react-scripts](https://github.com/JoV5/mult-react-scripts)，要新建项目的话就是`create-react-app appname --scripts-version mult-react-scripts`。
